/*
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.flow_dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractFlowDslValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(jp.hishidama.xtext.afw.flow_dsl.flowDsl.FlowDslPackage.eINSTANCE);
		return result;
	}
}
