/*
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.flow_dsl.ui.contentassist

import jp.hishidama.xtext.afw.flow_dsl.ui.contentassist.AbstractFlowDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FlowDslProposalProvider extends AbstractFlowDslProposalProvider {
}
