/**
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.batch_dsl.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class BatchDslQuickfixProvider extends DefaultQuickfixProvider {
}
