/*
* generated by Xtext
*/
package jp.hishidama.xtext.afw.flow_dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import jp.hishidama.xtext.afw.flow_dsl.services.FlowDslGrammarAccess;

public class FlowDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FlowDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected jp.hishidama.xtext.afw.flow_dsl.parser.antlr.internal.InternalFlowDslParser createParser(XtextTokenStream stream) {
		return new jp.hishidama.xtext.afw.flow_dsl.parser.antlr.internal.InternalFlowDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Script";
	}
	
	public FlowDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FlowDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
