/*
* generated by Xtext
*/
package jp.hishidama.xtext.afw.batch_dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BatchDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return jp.hishidama.xtext.afw.batch_dsl.ui.internal.BatchDslActivator.getInstance().getInjector("jp.hishidama.xtext.afw.batch_dsl.BatchDsl");
	}
	
}
