/*
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.batch_dsl.ui.contentassist

import jp.hishidama.xtext.afw.batch_dsl.ui.contentassist.AbstractBatchDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BatchDslProposalProvider extends AbstractBatchDslProposalProvider {
}
