/*
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.batch_dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import jp.hishidama.xtext.afw.batch_dsl.ui.internal.BatchDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BatchDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return BatchDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return BatchDslActivator.getInstance().getInjector(BatchDslActivator.JP_HISHIDAMA_XTEXT_AFW_BATCH_DSL_BATCHDSL);
	}
	
}
