/**
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.batch_dsl.ui.labeling;

import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for a IEObjectDescriptions and IResourceDescriptions.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class BatchDslDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
}
