/*
* generated by Xtext
*/
package jp.hishidama.xtext.afw.batch_dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import jp.hishidama.xtext.afw.batch_dsl.services.BatchDslGrammarAccess;

public class BatchDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private BatchDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected jp.hishidama.xtext.afw.batch_dsl.parser.antlr.internal.InternalBatchDslParser createParser(XtextTokenStream stream) {
		return new jp.hishidama.xtext.afw.batch_dsl.parser.antlr.internal.InternalBatchDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Script";
	}
	
	public BatchDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BatchDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
