/*
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.flow_dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FlowDslRuntimeModule extends jp.hishidama.xtext.afw.flow_dsl.AbstractFlowDslRuntimeModule {

}
