/*
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.batch_dsl.ui;

import jp.hishidama.xtext.afw.batch_dsl.ui.highlighting.BatchDslSemanticHighlightingCalculator;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BatchDslUiModule extends jp.hishidama.xtext.afw.batch_dsl.ui.AbstractBatchDslUiModule {
	public BatchDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		return BatchDslSemanticHighlightingCalculator.class;
	}
}
