/*
* generated by Xtext
*/
package jp.hishidama.xtext.afw.batch_dsl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BatchDslStandaloneSetup extends BatchDslStandaloneSetupGenerated{

	public static void doSetup() {
		new BatchDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

