/*
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.batch_dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BatchDslRuntimeModule extends jp.hishidama.xtext.afw.batch_dsl.AbstractBatchDslRuntimeModule {

}
