/**
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.batch_dsl.validation;

import jp.hishidama.xtext.afw.batch_dsl.validation.AbstractBatchDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BatchDslValidator extends AbstractBatchDslValidator {
}
