/*
 * generated by Xtext
 */
package jp.hishidama.xtext.afw.flow_dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import jp.hishidama.xtext.afw.flow_dsl.ui.internal.FlowDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FlowDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FlowDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FlowDslActivator.getInstance().getInjector(FlowDslActivator.JP_HISHIDAMA_XTEXT_AFW_FLOW_DSL_FLOWDSL);
	}
	
}
